services:
  web-app:
    build:  ./web-app/ # build from Dockerfile  
    ports:
     - 8000:5000
    volumes:
     - ./../web-app/web_app:/app
    depends_on:
     - BDD
     - Model_ML
     
     
  BDD:
    image:  postgres       #image déjà build
    ports:
     - 5430:5432
    environment:
     - POSTGRES_USER=wym_admin
     - POSTGRES_PASSWORD=admin
     
        
  Model_ML:
    image:  codait/max-text-summarizer # repo dockerhub par exemple
    ports:
     - 5000:5000
     
  streamlit_app:
    build: ./monitoring/
    ports:
     - 8501:8501
    depends_on:
     - web-app
     
